### ISSUE TITLE
dubbo-admin 标签规则无法按官方示例文档进行设置🆘

### ISSUE THREAD

**Issue by ranLee1** [apache/dubbo-admin#1268]
- [x] I have searched the [issues](https://github.com/apache/dubbo-admin/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [REAMDE](https://github.com/apache/dubbo-admin/blob/develop/README.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo Admin version: 0.5.0
* Registry center detail (type and version): Nacos：v2.2.1
* Operating System version: centos:7.9
* Java version: 17

### Steps to reproduce this issue
使用docker 搭建的dubbo-admin
1、在dubbo-admin中依次点击服务治理-标签路由-创建
2、添加官方标签路由示例
```yaml
configVersion: v3.0
force: true
enabled: true
key: shop-detail
tags:
  - name: gray
    match:
      - key: env
        value:
          exact: gray
```
3、点击保存后提示成功
4、在次编辑该标签路由显示结果：
```yaml
enabled: true
force: true
runtime: false
tags:
  - name: gray
    addresses: null

```
### Expected Result

![image](https://github.com/apache/dubbo-admin/assets/16217817/5694020d-e897-4cdf-a74c-3bd8eb6748ce)

### Actual Result

![image](https://github.com/apache/dubbo-admin/assets/16217817/d75e7b8d-79fd-405d-8016-46addcf3ff44)

**Comment by liujia13142324** [comment]
直接去改配置中心吧，这个管理后台约束做的太严格了

**Comment by ranLee1** [comment]
> 直接去改配置中心吧，这个管理后台约束做的太严格了

 @liujia13142324感谢您的回复，直接在配置中心修改是一个不错的方式，同时意味着后续编辑仅支持在配置中心操作，因为`dubbo-admin`获取配置时做了严格的格式限制，进而导致异常，如下图所示：
![image](https://github.com/apache/dubbo-admin/assets/16217817/6997932e-83ad-44af-bd7e-4cc3e13a4967)
`nacos`注册中心标签路由配置：
```yaml
enabled: true
force: true
key: platform-service
priority: 0
runtime: false
tags:
  - name: gray
    match:
      - key: env
        value:
          exact: gray
```
