### ISSUE TITLE
There is no metadata available, please update to Dubbo2.7, or check your config center configuration in application.properties, please check 

### ISSUE THREAD

**Issue by seedscoder** [apache/dubbo-admin#581]
- Environment:
   -  Spring Boot  version : 2.2.2.RELEASE
   -  Dubbo version : 2.7.5
   -  Dubbo Admin version : dubbo-admin-0.2.0

- Service Provider config :
```yml
dubbo:
  config-center:
    address: zookeeper://127.0.0.1:2181
  protocol:
    port: -1
    name: dubbo
```

- Zookeeper config : 
![zookeeper](https://user-images.githubusercontent.com/34568397/75654550-eda5b380-5c9a-11ea-8c20-e4d7fb599b66.jpg)

- Serivce Consumer config : 
```yml
dubbo:
  protocol:
    name: dubbo
    port: -1
  config-center:
    address: zookeeper://127.0.0.1:2181
```
- result : 
![dubbo admin](https://user-images.githubusercontent.com/34568397/75654271-4c1e6200-5c9a-11ea-921e-5e9f83b5dd9e.jpg)

I want to know what I need to do to see the results correctly, thanks

- I provided a demo project address
`https://github.com/seedscoder/dubbo-demo.git`
