### ISSUE TITLE
nacos 作为配置中心,admin 控制台获取不到服务信息

### ISSUE THREAD

**Issue by w935903854** [apache/dubbo-admin#667]
目前采用的是 springclouddubbo+nacos  
cloud 版本为2.2.0,对应 dubbo 版本为2.7.4.1,对应 nacos 版本为1.1.4,admin版本为 develop
![image](https://user-images.githubusercontent.com/59118285/99222538-c8070d00-281d-11eb-99d5-aab1558ba08e.png)
![image](https://user-images.githubusercontent.com/59118285/99222714-161c1080-281e-11eb-8e33-f472c535b1a2.png)

**Comment by nickszeng** [comment]
+1 同困扰

**Comment by tanyouxiang** [comment]
+1希望支持nacos

**Comment by kzhan** [comment]
+1
这块都不活跃的吗

**Comment by imarkofu** [comment]
+1

**Comment by xielinjiang2008** [comment]
+1

**Comment by KeRan213539** [comment]
这个问题目前已修复,拉最新代码试下

**Comment by codelearner1024** [comment]
> 这个问题目前已修复,拉最新代码试下

最新拉取的是以下这些，并未看到您提交的哇，请指教：

修复mvn install时前端编译报错问题 (#680) 邪影oO* 2021\1\19 0019 20:07
修复sh脚本问题 (#679) 邪影oO* 2021\1\19 0019 13:18
fix #677 dubbo admin 修改打包结构,增加启动脚本 (#678) 邪影oO* 2021\1\18 0018 16:55

**Comment by KeRan213539** [comment]
https://github.com/apache/dubbo-admin/pull/638 是这个PR. 如果这个PR没解决的话,还请多提供点具体信息一遍复现定位
顺便说一下,如果是用了应用级服务发现的话, admin这边暂时还不支持,不过已经准备搞这块了

**Comment by codelearner1024** [comment]
> #638 是这个PR. 如果这个PR没解决的话,还请多提供点具体信息以便复现定位
> 顺便说一下,如果是用了应用级服务发现的话, admin这边暂时还不支持,不过已经准备搞这块了

好的 ，再细测一遍

**Comment by KeRan213539** [comment]
> > #638 是这个PR. 如果这个PR没解决的话,还请多提供点具体信息以便复现定位
> > 顺便说一下,如果是用了应用级服务发现的话, admin这边暂时还不支持,不过已经准备搞这块了
> 
> 好的 ，再细测一遍

嗯嗯,辛苦 :)

**Comment by codelearner1024** [comment]
> > > #638 是这个PR. 如果这个PR没解决的话,还请多提供点具体信息以便复现定位
> > > 顺便说一下,如果是用了应用级服务发现的话, admin这边暂时还不支持,不过已经准备搞这块了
> > 
> > 
> > 好的 ，再细测一遍
> 
> 嗯嗯,辛苦 :)

 貌似搞不起来！！！

dubbo-admin 代码拉了最新的，我的yml 配置 dubbo部分是这样的

``` yaml
dubbo:
  scan:
    base-packages: com.ecb.emc.service
  protocol:
    host: localhost
    name: dubbo
    port: -1
  registry:
    # 挂载到 Spring Cloud 注册中心
#    address: spring-cloud://localhost
    address: nacos://127.0.0.1:8848
    group: dubbo
    protocol: nacos
  consumer:
    check: false
    group: dubbo
  cloud:
    subscribed-services: '*'
  config-center:
    group: dubbo
    namespace: dubbo
  metadata-report:
    group: dubbo
  provider:
    group: dubbo
  monitor:
    group: dubbo
```


我bootstrap.yml的配置如下：
``` yaml
# DataId 默认使用 `spring.application.name` 配置跟文件扩展名结合(配置格式默认使用 properties),
# GROUP 不配置默认使用 DEFAULT_GROUP。因此该配置文件对应的 Nacos Config 配置的
# DataId 为 nacos-config.properties, GROUP 为 DEFAULT_GROUP
spring:
  application:
    name: xxx
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
```


工程依赖如下：

```
buildscript {
    ext {
        springBootVersion = '2.2.9.RELEASE'
    }
    repositories {
        maven { url 'http://maven.aliyun.com/nexus/content/groups/public/' }
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
    }
}

repositories {
    mavenLocal()
}

allprojects {
    group = 'xxxx'
    version = '1.0'
    apply plugin: 'idea'
    apply plugin: 'eclipse'
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'org.springframework.boot'
    apply plugin: 'io.spring.dependency-management'
    sourceCompatibility = '1.8'
    [compileJava, compileTestJava, javadoc]*.options*.encoding = 'UTF-8'

    repositories {
        maven {
            url = 'https://maven.aliyun.com/repository/public'
        }
    }

    ext {
        set('springCloudAlibabaVersion', "2.2.1.RELEASE")
        set('springCloudVersion', "Hoxton.SR3")
    }

    dependencies {
        implementation 'org.springframework.boot:spring-boot-starter-web'
        implementation 'org.springframework.boot:spring-boot-starter-actuator'
        implementation 'org.springframework.data:spring-data-redis'
        implementation 'org.springframework.data:spring-data-mongodb'
        implementation 'com.alibaba.cloud:spring-cloud-starter-dubbo'
        implementation 'org.apache.dubbo:dubbo:2.7.8'
        implementation 'com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-discovery'
        implementation 'com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-config'
        implementation 'com.alibaba:druid-spring-boot-starter:1.1.23'
        implementation 'org.apache.rocketmq:rocketmq-spring-boot-starter:2.1.1'
        implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:2.1.3'
        implementation 'redis.clients:jedis:3.3.0'
        implementation 'com.itextpdf:itextpdf:5.5.9'
        implementation 'com.itextpdf:itext-asian:5.2.0'
        implementation 'fr.opensagres.xdocreport:org.apache.poi.xwpf.converter.pdf:1.0.4'
        implementation 'fr.opensagres.xdocreport:fr.opensagres.xdocreport.itext.extension:1.0.4'
    
        runtimeOnly 'mysql:mysql-connector-java'
        testCompile('org.springframework.boot:spring-boot-starter-test') {
            exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
        }

    }

    dependencyManagement {
        imports {
            mavenBom "com.alibaba.cloud:spring-cloud-alibaba-dependencies:${springCloudAlibabaVersion}"
            mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
        }
    }

}


```
