### ISSUE TITLE
服务统计无法使用，元数据注册节点和配置节点都分开了

### ISSUE THREAD

**Issue by JokerDevops** [apache/dubbo-admin#702]
服务统计无法使用。
只能看到服务查询，其他的都不好使，我在 zk 里面 /dubbo/config/dubbo/dubbo.properties 设置了 “DUBBO_REGISTRY_ADDR” 和 “DUBBO_METADATA_ADDR”  配置文件里面设置了 admin.config-center=zookeeper://192.168.0.203:2182  还是不能使用。

**Comment by KeRan213539** [comment]
服务统计需要在提供者中启用统计功能, 引入
```xml
<dependency>
    <groupId>org.apache.dubbo</groupId>
    <artifactId>dubbo-monitor-default</artifactId>
    <version>${dubbo.version}</version>
</dependency>
```
并增加配制
```yaml
dubbo:
  metrics:
    port: ${dubbo.protocol.port}
    protocol: dubbo
```
